version: "2.0"
nlu:
- intent: list_releases
  examples: |
    - what are the releases in this repository
- intent: issue_assignees
  examples: |
    - Who are the assignees on issue [1](issue_number)
    - Who is assigned to issue [64](issue_number)
- intent: developers_with_most_open_issues
  examples: |
    - I want to have a list of developers with open issues
    - give me a list of developers with the most open issues
- intent: last_developer_to_touch_a_file
  examples: |
    - show me the last person to change [actions.java](filename)
    - who last commited with file [readme.md](filename)
- intent: pr_assignees
  examples: |
    - Who should fix pull request [1](issue_number)
    - which developers should work on pull request [5](issue_number)
- intent: list_languages
  examples: |
    - list me the language of this repostiory
    - What are the technologies that are used in this repository ?
- intent: number_of_commits_in_branch
  examples: |
    - count the number of commits in branch TheBranch
    - how many commits are in the branch rel-1.3.0?
    - number of commits in the branch the-branch-name
- intent: number_of_collaborators
  examples: |
    - How many collaborators ?
    - number of collaborators
- intent: intial_commit_in_branch
  examples: |
    - first commit in branch X
    - when was the first commit made in the master branch
    - who has the first commit in branch xxyx
- intent: contributions_by_developer
  examples: |
    - How many contributions does Makram have
    - What is the total number of contributions that Linus has made to this repository
- intent: commits_in_pr
  examples: |
    - show me pull request [84161](issue_number) related commits
    - pr [13](issue_number) related commits
    - what are the commits in pull request [964](issue_number)
- intent: largest_files
  examples: |
    - What is the biggest file in the repository
    - List me the file with the most lines of code
- intent: latest_commit
  examples: |
    - the most recent commit
    - tell me what the last pushed commit is
    - can you tell me what the latest commit was
- intent: latest_commit_in_branch
  examples: |
    - what is the last commit in the clean_tool branch
    - who commited last in the feature_2 branch
- intent: latest_release
  examples: |
    - latest release
    - when was the latest release published
    - what is the newest code release
- intent: longest_open_pr
  examples: |
    - which pr has remained unmerged the longest period of time
    - longest open pr
    - which pr has been open for the longest time
- intent: longest_open_issue
  examples: |
    - which issue has been open the longest
    - which issue has been left unresolved for the most amount of time ?
    - which issue has been open for the longest time
- intent: activity_report
  examples: |
    - Give me the daily report
    - What happened in the last 24 hours
    - daily report
- intent: issue_creation_date
  examples: |
    - when did we open issue [4783](issue_number)
    - when was issue [24](issue_number) created
    - issue [546](issue_number) creation date
- intent: pr_creation_date
  examples: |
    - At what time was the pull request [2315](issue_number) opened
    - When was pull request [1109](issue_number) opened
    - when was pr [24](issue_number) created
- intent: intial_commit
  examples: |
    - who authored the 1st commit
    - can you tell me what the intial commit was
    - when was the first commit made
    - who has the initial commit in the repository
- intent: number_of_prs
  examples: |
    - How many prs are currently [open](issue_status)
    - please provide a report about [closed](issue_status) pull requests in the repo
    - How many [open](issue_status) prs
- intent: number_of_issues
  examples: |
    - How many [open](issue_status) issues
    - How many bugs are currently [open](issue_status)
    - Give me the total number of issues in the repository
    - count issues
- intent: files_changed_by_pr
  examples: |
    - list me the files affected by pr number [4](issue_number)
    - give me a list of files that were changed by pull request [564](issue_number)
    - file diff for PR [89](issue_number)
- intent: top_contributors
  examples: |
    - who has the highest number of commits
    - who are the developers with the most contributions to this repository
    - who are the active developers?
    - show me the list of the top contributers
- intent: most_recent_prs
  examples: |
    - list the recent open pull requests
    - newest prs
    - give me a list of new pull requests
    - show me the latest prs
- intent: most_recent_issues
  examples: |
    - list recent issues
    - list the recent open issues
    - what are the most recent issues
    - newest issues
- intent: pr_closing_date
  examples: |
    - What was the date of closing pr [4](issue_number)
    - when did we merge pr [3907](issue_number)
    - when did we close pr [4783](issue_number)
    - When was pull request [1109](issue_number) closed
- intent: issue_creator
  examples: |
    - who created issue [6744](issue_number)
    - issue [13](issue_number) creator
    - show me issue [84161](issue_number) creator
    - give me the user that opened issue [888](issue_number)
- intent: pr_contributors
  examples: |
    - who contributed to pr [6744](issue_number)
    - show me the developers who commented on pr [888](issue_number)
    - pr [774](issue_number) commenters
    - give me a list of developers who contributed to pr [564](issue_number)
- intent: pr_closer
  examples: |
    - give me the user that merged pr [888](issue_number)
    - pr [774](issue_number) merger
    - show me pull request [84161](issue_number) closer
    - give me a the developer name who closed pull request [564](issue_number)
- intent: issue_closing_date
  examples: |
    - What was the date when issue [432](issue_number) was resolved
    - issue [546](issue_number) closing date
    - What was the date of closing issue [4](issue_number)
    - When did issue [214](issue_number) finally close
- intent: pr_creator
  examples: |
    - pr [774](issue_number) opener
    - show me who opned pull request [1235](issue_number)
    - pr [13](issue_number) creator
    - who created pull request [6744](issue_number)
    - who authored pull request [3](issue_number)?
- intent: issue_closer
  examples: |
    - who closed issue [6744](issue_number)
    - closer of issue [3234](issue_number)
    - who resolved issue [6744](issue_number)
    - give me the user that resolved issue [888](issue_number)
- intent: number_of_watchers
  examples: |
    - how many watchers in total does the repository have?
    - how many watchers for the repository?
    - count the repository watchers
    - watchers count?
    - how many watchers
- intent: default_branch
  examples: |
    - what is the base branch in the repository
    - Which branch is considered to be the base one?
    - which branch is deafualt out of the ones we have?
    - let me know which branch is the main one?
- intent: main_programming_language
  examples: |
    - Main programming language?
    - what is the main language in the repository?
    - I'd like to know the most used programming language
    - which programming language do we use the most?
    - let me know which programming language is most used
- intent: repository_owner
  examples: |
    - who has ownership over this repository
    - can you give me the name of the repository owner
    - I'd like to know the repository owner
    - can you provide me with the repo owner
- intent: repository_license
  examples: |
    - legal license?
    - what is the repository legal license?
    - what is the legal license in this repository?
    - What licences do we have?
    - can I know the licences of the repository
- intent: issue_contributors
  examples: |
    - show me the developers who commented on issue [888](issue_number)
    - give me names of all the commenters on issue [6681](issue_number)
    - issue [13](issue_number) contributors
    - show me who helped on issue [1235](issue_number)
    - who are the contributors to issue [964](issue_number)
- intent: repository_topics
  examples: |
    - what are the topics for the repository ?
    - can you give me the topics related to this repository
    - give me the topics that are related to repository
    - what topics are related to our repository?
    - I would like to know the topics in the repository we have
    - list me all the topics for this repository
- intent: repository_creation_date
  examples: |
    - give me the repository creation date
    - I want to know th ecreation date of repository
    - at what time was this repository created
    - When did this project start?
    - when did this repository start
- intent: file_creator
  examples: |
    - who created [map.json](filename)?
    - who created file [index.js](filename)?
    - who added the file [response.java](filename) ?
    - who was the creator of this file [server.rb](filename)?
    - give me the name of the developer who created file [index.html](filename)
    - who created this file [index.js](filename)
    - I want to know who created file [map.json](filename)
- intent: issue_related_commits
  examples: |
    - issue [13](issue_number) linked commits?
    - list commits that mention issue [84161](issue_number)
    - in which commits was issue [964](issue_number)?
    - issue [13](issue_number) related commits?
    - give me a the commits linked to issue [564](issue_number)
    - give me the commits that mentioned issue [888](issue_number)?
- intent: list_branches
  examples: |
    - what branches do I have
    - what are the branches that are in the repository?
    - what branches do I have in repository?
    - what branches are available right now?
    - give me a list of all the branches in the repository
    - what branches do we have in repository
    - what are the available branches?
- intent: number_of_branches
  examples: |
    - how many branches do we have?
    - I want to know the number of branches in the repository
    - let me know how many branches are in the repository
    - How many branches?
    - I would like to know how many branches are there in total?
    - how many branches
    - how many branches in total does the repository have?
    - please let me know the number of branches in the repo
- intent: number_of_commits
  examples: |
    - count the repository commits
    - how many commits do we have?
    - total number of commits?
    - count for me the number of commits that I have
    - how many commits in total does the repository have?
    - how many commits do I have?
    - commits count?
    - what is the number of commits that we have?
    - how many commits in total?
- intent: number_of_forks
  examples: |
    - how many forks
    - give the number of forks I have in repository
    - how many forks in total does the repository have?
    - count the repository forks
    - what is the number of forks
    - I want to know the number of forks in the repository
    - how many forks in total?
    - number of forks
- intent: number_of_stars
  examples: |
    - how many stars do we have?
    - give the number of stars I have in repository
    - how many stars in the repository?
    - count the repository stars
    - give me a count of all the stars
    - stars count?
    - total number of stars?
    - what is the number of stars that we have?
    - please let me know the number of stars in the repo
- intent: number_of_subscribers
  examples: |
    - give me a count of all the subscribers
    - in this repository what is the total count of subscribers
    - subscribers count?
    - provide me with the total number of subscribers
    - number of subscribers
    - I would like to know how many subscribers are there in total?
    - How many subscribers?
    - how many subscribers do I have
    - how many subscribers do we have?
- intent: list_collaborators
  examples: |
    - list all the people who worked on the project
    - who worked on this repository?
    - Who are the repository contributors?
    - list the names of all the contributors?
    - give me all the contributors?
    - who are the collaborators?
    - tell me who worked on the repository
    - list me all the people who helped in this project?
    - give me a list of all the collaborators to the repository
- intent: number_of_downloads
  examples: |
    - count all the downloads for me
    - in this repository what is the total count of downloads
    - count repository downloads
    - provide me with the total number of downloads
    - count the repository downloads
    - how many downloads do I have?
    - total number of downloads?
    - give the number of downloads I have in repository
    - number of downloads
    - downloads count?
- regex: filename
  examples: |
    - [^\\ ]*\.(\w+)
- regex: number
  examples: |
    - [0-9]+
