version: "2.0"
nlu:
- intent: issue_assignees
  examples: |
    - Who should fix issue [1](issue_number)
- intent: developers_with_most_open_issues
  examples: |
    - give me a list of developers with the most open issues
- intent: list_releases
  examples: |
    - can you list the releases we have
- intent: last_developer_to_touch_a_file
  examples: |
    - developer who most recently changed [constant.txt](filename)
    - show me the last person to change [actions.java](filename)
- intent: number_of_commits_in_branch
  examples: |
    - count the number of commits in branch TheBranch
- intent: pr_assignees
  examples: |
    - Who are the assignees on pr [1](issue_number)
- intent: number_of_collaborators
  examples: |
    - how many contributors does this repository have
    - How many collaborators ?
- intent: list_languages
  examples: |
    - list the languages
    - What are the top languages in this repostiory ?
- intent: intial_commit_in_branch
  examples: |
    - what was the message of the first commit in branch master
- intent: contributions_by_developer
  examples: |
    - What is the total number of contributions that Linus has made to this repository
    - How many commits has Khaled made
- intent: commits_in_pr
  examples: |
    - what are the commits in pull request [964](issue_number)
- intent: largest_files
  examples: |
    - biggest file
    - large files
- intent: latest_release
  examples: |
    - when did we last create a new release
    - what is the newest code release
- intent: latest_commit
  examples: |
    - the most recent commit
    - when was the last commit made
- intent: latest_commit_in_branch
  examples: |
    - can you tell me what the latest commit was in this branch play_tests
    - who commited last to the master branch
- intent: longest_open_pr
  examples: |
    - pull request that has been open for a long time
- intent: longest_open_issue
  examples: |
    - issue that has been open for a long time
    - which issue has been open for the longest time
- intent: activity_report
  examples: |
    - What were the recent events in the repository
    - daily report
- intent: issue_creation_date
  examples: |
    - can you tell me the date [2](issue_number) was opened ?
    - What was the date when issue [432](issue_number) was created
    - when was issue [24](issue_number) created
- intent: intial_commit
  examples: |
    - who made the 1st commited
    - first commit
- intent: number_of_prs
  examples: |
    - what is the number of [closed](issue_status) pull requests
    - count [open](issue_status) pull requests
- intent: pr_creation_date
  examples: |
    - When did pull request [214](issue_number) open
    - pr [546](issue_number) creation date
- intent: number_of_issues
  examples: |
    - number of [closed](issue_status) issues
    - number of issues
    - Give me the bugs report
- intent: most_recent_prs
  examples: |
    - list recent prs
    - most recent pull requests
- intent: files_changed_by_pr
  examples: |
    - In pull request [6744](issue_number), what files changed
    - show me a list of changed files in pr [6744](issue_number)
- intent: most_recent_issues
  examples: |
    - give me a list of new issues
    - newest issues
    - what are the most recent issues
- intent: top_contributors
  examples: |
    - who are the active developers?
    - who has the highest number of commits
    - Who committed the most to this repository
- intent: pr_closing_date
  examples: |
    - when was pull request [674](issue_number) merged
    - when was pr [24](issue_number) closed
- intent: issue_closing_date
  examples: |
    - issue [546](issue_number) closing date
    - was issue [24](issue_number) closed ?
    - When did issue [214](issue_number) finally close
- intent: issue_creator
  examples: |
    - show me who created issue [74](issue_number)
    - give me the user that opened issue [888](issue_number)
    - who opened issue [9521](issue_number)
- intent: pr_contributors
  examples: |
    - pr [774](issue_number) commenters
    - give me a list of developers who contributed to pr [564](issue_number)
    - show me pr [84161](issue_number) contributors
- intent: pr_creator
  examples: |
    - who opened pr [9521](issue_number)
    - give me a the developer name who created pull request [564](issue_number)
- intent: pr_closer
  examples: |
    - who merged pr [3234](issue_number)
    - pr [774](issue_number) merger
    - show me who closed pull request [1235](issue_number)
- intent: issue_closer
  examples: |
    - who is the developer that resolved issue [964](issue_number)
    - issue [774](issue_number) resolver
    - show me who closed issue [74](issue_number)
- intent: number_of_watchers
  examples: |
    - I want to know the number of people watching the the repository
    - how many watchers
    - number of watchers?
- intent: default_branch
  examples: |
    - Which branch is considered as default
    - I would like to know the default branch
    - Default branch?
- intent: main_programming_language
  examples: |
    - give me the main programming language
    - what is the main language of this repository
    - which language are we using the most?
- intent: repository_owner
  examples: |
    - Who owns the repository?
    - what is the name of the repository owner?
    - which user owns this repository
- intent: repository_license
  examples: |
    - what licences do I have in the repository?
    - give me the license for the repository
    - can I know the licences of the repository
- intent: issue_contributors
  examples: |
    - show me who contributed to issue [74](issue_number)
    - show me the developers who commented on issue [888](issue_number)
    - who worked on [33](issue_number)
    - give me a list of developers who contributed to issue [564](issue_number)
- intent: repository_topics
  examples: |
    - what topics are related to our repository?
    - I'd like to know the repository topics
    - I would like to know the topics in the repository we have
- intent: repository_creation_date
  examples: |
    - At what time was this project started?
    - at what time was this repository created
    - what is the creation dete for the repository
    - when did we create the repository
- intent: file_creator
  examples: |
    - who added the file [response.java](filename) ?
    - I would like to know who first created file [tf_env_collect.sh](filename)?
    - who created file [index.js](filename)?
    - give me the name of the developer who created file [index.html](filename)
- intent: issue_related_commits
  examples: |
    - which commits in the repository are related to issue [84161](issue_number)?
    - show me the linked commits to issue [84161](issue_number)
    - list commits that mention issue [84161](issue_number)
    - what commits are linked to [3234](issue_number)?
    - commits linked to issue [3234](issue_number)
- intent: list_branches
  examples: |
    - what are the branches in the repository
    - what branches do we have?
    - list all branches please
    - give me the branches that we have
- intent: number_of_branches
  examples: |
    - how many branches in the repository?
    - count for me the number of branches that I have
    - how many branches in total does the repository have?
    - How many branches?
    - how many branches in total?
    - please let me know the number of branches in the repo
- intent: number_of_commits
  examples: |
    - give me a count of all the commits
    - what is the number of commits
    - how many commits in total?
    - in this repository what is the total count of commits
    - number of commits?
    - count for me the number of commits
- intent: number_of_stars
  examples: |
    - provide me with the total number of stars
    - give the number of stars I have in repository
    - how many stars in the repository?
    - In this repository, how many stars do I have?
    - how many stars in total?
- intent: number_of_forks
  examples: |
    - count all the forks for me
    - how many forks do I have
    - how many forks in the repository?
    - number of forks?
    - how many forks in total does the repository have?
    - in this repository what is the total count of forks
- intent: number_of_subscribers
  examples: |
    - number of subscribers?
    - subscribers count?
    - count all the subscribers for me
    - let me know how many subscribers are in the repository
    - how many subscribers in the repository?
    - I want to know the number of subscribers in the repository
- intent: list_collaborators
  examples: |
    - list all the contributors
    - list who worked on this project
    - Who committed in this repository?
    - please give me the names of the repository collaborators
    - who collaborated in the repository?
    - who contributed to our project?
- intent: number_of_downloads
  examples: |
    - what is the number of downloads that we have?
    - how many downloads do I have
    - How many downloads?
    - how many downloads do we have?
    - how many downloads do I have?
    - how many downloads in total does the repository have?
- regex: filename
  examples: |
    - [^\\ ]*\.(\w+)
- regex: number
  examples: |
    - [0-9]+
