version: "2.0"
nlu:
- intent: issue_assignees
  examples: |
    - Who is the assignee on issue [121](issue_number)
    - assignee of issue [24](issue_number)
    - who is supposed to fix issue [62](issue_number)
- intent: developers_with_most_open_issues
  examples: |
    - I want to have a list of developers with open issues
    - who is assigned to the largest number of open issues
    - give me a list of developers with the most open issues
- intent: list_releases
  examples: |
    - give me a list of the releases in the repository
    - I want a list of repository releases
    - can you list the releases we have
- intent: last_developer_to_touch_a_file
  examples: |
    - who last commited with file [readme.md](filename)
    - for file [map.json](filename) who was the last to touch it
    - show me the last person to change [actions.java](filename)
- intent: number_of_commits_in_branch
  examples: |
    - count the number of commits in branch TheBranch
    - commits in branch xywz
    - How many commits are in the development branch
    - how many commits are in branch X
- intent: pr_assignees
  examples: |
    - Who are the assignees on pr [1](issue_number)
    - Who is the assignee on the pull request [121](issue_number)
    - assignee of pr [24](issue_number)
- intent: number_of_collaborators
  examples: |
    - number of contributers
    - How many collaborators ?
    - how many contributors does this repository have
    - How many developers have worked on this repository ?
- intent: list_languages
  examples: |
    - What are the programming languages used in the repo
    - list the languages
    - top languages
    - list me the language of this repostiory
- intent: intial_commit_in_branch
  examples: |
    - the inital commit for branch dev1
    - who has the first commit in branch xxyx
    - what was the message of the first commit in branch master
    - first commit in branch X
- intent: contributions_by_developer
  examples: |
    - How many commits has Khaled made
    - How much did John contribute to the respository ?
    - Did Ben make alot of contributions to this repository ?
    - How many commits does George have
- intent: commits_in_pr
  examples: |
    - show me commits linked to pr [74](issue_number)
    - what are the commits in pull request [964](issue_number)
    - pr [13](issue_number) related commits
    - what are the commits linked to pr [6744](issue_number)
- intent: largest_files
  examples: |
    - longest file size
    - large files
    - List me the file with the most lines of code
    - Bigest file in the repository
    - biggest file
- intent: latest_release
  examples: |
    - what is the newest code release
    - when was the latest release published
    - latest release
    - what is the latest release for the repository
- intent: latest_commit
  examples: |
    - what is the last commit in the repository
    - the most recent commit
    - the latest commit
    - who made the last commit
    - when was the last commit made
- intent: latest_commit_in_branch
  examples: |
    - who commited last to the master branch
    - can you tell me what the latest commit was in this branch play_tests
    - when was the last commit made in ths branch
    - what is the last commit in the clean_tool branch
- intent: longest_open_pr
  examples: |
    - which pr has been open the longest
    - pull request that has been open for a long time
    - show me the longest open pull request
    - Which pull requet has stayed open the longest
    - which pr has remained unmerged the longest period of time
- intent: longest_open_issue
  examples: |
    - oldest open issue ?
    - issue that has been open for a long time
    - longest open issue
    - which issue has been left unresolved for the most amount of time ?
    - which issue has been open for the longest time
- intent: activity_report
  examples: |
    - what were the main events from the last day
    - give me a report from the last day?
    - what happened yesterday
    - progress report
    - What happened in the last 24 hours
- intent: issue_creation_date
  examples: |
    - What was the date when issue [432](issue_number) was created
    - when was issue [24](issue_number) created
    - show me the creation date for issue [3](issue_number)
    - can you tell me the date [2](issue_number) was opened ?
    - At what time was issue [2315](issue_number) opened
- intent: intial_commit
  examples: |
    - who authored the 1st commit
    - first commit
    - what is the first commit in the repository
    - who commited first to the repo
    - the inital commit
    - what is the first commit ever
- intent: number_of_prs
  examples: |
    - count [open](issue_status) pull requests
    - I want to know the number of pulls
    - For this repo, show me the the number of [open](issue_status) prs
    - Give me the total number of pulls in the repository
    - How many prs are currently [open](issue_status)
- intent: pr_creation_date
  examples: |
    - What was the date of creation for pr [4](issue_number)
    - when was pr [24](issue_number) created
    - When did pull request [214](issue_number) open
    - pr [546](issue_number) creation date
    - At what time was the pull request [2315](issue_number) opened
    - pull request [546](issue_number) creation date
- intent: number_of_issues
  examples: |
    - Give me the bugs report
    - How many [open](issue_status) issues
    - count issues
    - number of issues
    - number of [closed](issue_status) issues
    - For this repo, show me the the number of [open](issue_status) issues
- intent: most_recent_prs
  examples: |
    - show me the latest prs
    - list the recent open pull requests
    - what are the newest prs
    - show me the most recent prs
    - list recent prs
    - most recent pull requests
- intent: files_changed_by_pr
  examples: |
    - pr [13](issue_number) changed files
    - file diff for PR [89](issue_number)
    - what files were changed in pr [6744](issue_number)
    - give me a list of files that were changed by pull request [564](issue_number)
    - In pull request [6744](issue_number), what files changed
    - show me a list of changed files in pr [6744](issue_number)
- intent: most_recent_issues
  examples: |
    - what are the newest issues
    - show me the most recent issues
    - latest issues
    - what are the most recent issues
    - newest issues
    - latest opened issues
- intent: top_contributors
  examples: |
    - contributors by commits
    - which developer contributed the most to the repository
    - show me the list of the top contributers
    - who are the top 10 contributors
    - who has the most contributions in this repostiory
    - who are the active developers?
    - who are the developers with the most contributions to this repository
- intent: pr_closing_date
  examples: |
    - At what time was pull request [2315](issue_number) closed
    - pr [546](issue_number) closing date
    - when was pull request [674](issue_number) merged
    - When was pull request [1109](issue_number) closed
    - closing date pull request [860](issue_number)
    - When did pr [214](issue_number) finally close
- intent: issue_closing_date
  examples: |
    - when was issue [24](issue_number) closed
    - show me the closing date for issue [3](issue_number)
    - when did we resolve issue [3907](issue_number)
    - When did issue [214](issue_number) finally close
    - when did we close issue [4783](issue_number)
    - closing date issue [860](issue_number)
    - issue [546](issue_number) closing date
- intent: issue_creator
  examples: |
    - who created issue [9521](issue_number)
    - who opened issue [6744](issue_number)
    - who created issue [6744](issue_number)
    - show me who created issue [74](issue_number)
    - creator of issue [3234](issue_number)
    - give me a the developer name who created issue [564](issue_number)
    - issue [774](issue_number) opener
- intent: pr_contributors
  examples: |
    - contributors to pr [3234](issue_number)
    - pr [774](issue_number) commenters
    - give me a list of developers who contributed to pr [564](issue_number)
    - show me who contributed to pr [74](issue_number)
    - list all the developers who commented on pr [3](issue_number)
    - give me names of all the contributors to pr [123](issue_number)
    - show me the developers who commented on pr [888](issue_number)
- intent: pr_creator
  examples: |
    - creator of pull request [3234](issue_number)
    - who is the developer that started pull request [964](issue_number)
    - who created pull request [6744](issue_number)
    - give me the user that opened pr [888](issue_number)
    - show me who created pr [74](issue_number)
    - pr [774](issue_number) opener
    - pr [13](issue_number) creator
- intent: pr_closer
  examples: |
    - merger of pr [9521](issue_number)
    - give me the user that merged pr [888](issue_number)
    - who closed pull request [6744](issue_number)
    - closer of pull request [3234](issue_number)
    - show me who closed pull request [1235](issue_number)
    - give me a the developer name who closed pull request [564](issue_number)
    - show me pull request [84161](issue_number) closer
- intent: issue_closer
  examples: |
    - issue [774](issue_number) resolver
    - who closed issue [6744](issue_number)
    - who is the developer that resolved issue [964](issue_number)
    - who closed issue [9521](issue_number)
    - who resolved issue [9521](issue_number)
    - show me who closed issue [1235](issue_number)
    - who is responsible for closing issue [44](issue_number)
    - who resolved issue [6744](issue_number)
- intent: number_of_watchers
  examples: |
    - how many watchers for the repository?
    - count for me the number of watchers
    - how many watchers in total does the repository have?
    - number of watchers?
    - how many watchers do we have?
    - count the repository watchers
    - watchers count
- intent: default_branch
  examples: |
    - Which branch is considered as default
    - let me know which branch is the main one?
    - main branch?
    - Which branch is considered to be the base one?
    - what is the default branch
    - what is the main branch in this repository
    - I would like to know the default branch
    - what is the base branch in this repository?
- intent: main_programming_language
  examples: |
    - which programming language do we use the most?
    - I'd like to know the main programming language
    - let me know which programming language is most used
    - which language are we using the most?
    - what is the main language
    - What programming language is most used in this repository
    - give me the main programming language
- intent: repository_owner
  examples: |
    - can you give me the name of the repository owner
    - Who owns the repository?
    - what is the name of the repository owner?
    - who owns the repository?
    - who owns repository?
    - Who is the repository owner
    - which user owns this repository
    - tell me the name of the repository owner
- intent: repository_license
  examples: |
    - repository license
    - what is the legal license in this repository?
    - what is the license for the repository ?
    - can I know the licences of the repository
    - what licences do I have in the repository?
    - what is the repository legal license?
    - Under which license does the repository work
    - give me the license for the repository
- intent: issue_contributors
  examples: |
    - issue [774](issue_number) commenters
    - contributors to issue [3234](issue_number)
    - who touched [98](issue_number)
    - list all the developers who commented on issue [3](issue_number)
    - who are the people who commented on issue [9521](issue_number)
    - who contributed to issue [6744](issue_number)
    - show me the developers who commented on issue [888](issue_number)
    - show me who helped on issue [1235](issue_number)
- intent: repository_topics
  examples: |
    - give me the topics that are related to repository
    - what topics are there ?
    - repository topics that we have?
    - I'd like to know the repository topics
    - what are the repository topics
    - what topics does my repository have?
    - what topics do we have in this repository?
    - what topics are related to our repository?
    - list me all the topics for this repository
- intent: repository_creation_date
  examples: |
    - what is the creation dete for the repository
    - I would like to know the date that we start this project
    - At what time was this project started?
    - I want to know th ecreation date of repository
    - I want to know when was the repository created?
    - When did I start the project?
    - give me the repository creation date
    - when did this repository start
    - when was this repository created?
    - when was our repo created?
- intent: file_creator
  examples: |
    - who created file [pyproject.toml](filename) in repository
    - tell me the developer name who created file [gitignore](filename)
    - which developer started file [actions.java](filename)?
    - give me the name of the developer who created file [index.html](filename)
    - who first added this file [domain.yml](filename) ?
    - who created file [readme.md](filename) in the repository?
    - who created [map.json](filename)?
    - who created file [actions.java](filename) in my project
    - name the developer who created file [users.db](filename)
    - who created this file [index.js](filename)
- intent: issue_related_commits
  examples: |
    - give me a the commits related to issue [564](issue_number)
    - show me commits related to this issue [3234](issue_number)?
    - list me the commits that mentioned issue [888](issue_number)
    - show me commits linked to this issue [3234](issue_number)?
    - in which commits was issue [964](issue_number)?
    - commits related to issue [3234](issue_number)
    - give me a the commits linked to issue [564](issue_number)
    - give me the commits that mentioned issue [888](issue_number)?
    - what commits were mentioned issue [74](issue_number)?
    - which commits in the repository are related to issue [84161](issue_number)?
    - show me the linked commits to issue [84161](issue_number)
- intent: list_branches
  examples: |
    - what branches do we have in repository
    - list all branches please
    - I want to know the names of the branches in the repository
    - list the names of branches
    - list all the branches names
    - what are the branches that are in the repository?
    - Give me a list of the branches
    - give me a list of all the branches in the repository
    - what are the names of all the branches
    - what branches do we have?
    - give me a list of the names of all branches in the repo?
- intent: number_of_branches
  examples: |
    - number of branches?
    - what is the number of branches that we have?
    - how many branches
    - give me a count of all the branches
    - count for me the number of branches that I have
    - branches count?
    - count for me the number of branches
    - total number of branches?
    - how many branches in the repository?
    - number of branches
    - how many branches in total?
    - In this repository, how many branches do I have?
    - in this repository what is the total count of branches
    - how many branches do I have?
- intent: number_of_commits
  examples: |
    - count for me the number of commits
    - How many commits?
    - count all the commits for me
    - total number of commits?
    - provide me with the total number of commits
    - how many commits do I have
    - please let me know the number of commits in the repo
    - commits count
    - in this repository what is the total count of commits
    - how many commits do we have?
    - how many commits in the repository?
    - what is the number of commits
    - number of commits?
    - let me know how many commits are in the repository
    - give the number of commits I have in repository
- intent: number_of_stars
  examples: |
    - number of stars
    - count all the stars for me
    - I would like to know how many stars are there in total?
    - total number of stars?
    - give me the star count in my repoisotry
    - what is the number of stars
    - I want to know the number of stars in the repository
    - how many stars
    - number of stars?
    - how many stars do I have
    - in this repository what is the total count of stars
    - how many stars in the repository?
    - how many stars in total?
    - How many stars?
- intent: number_of_forks
  examples: |
    - total number of forks?
    - give the number of forks I have in repository
    - How many forks?
    - count for me the number of forks
    - what is the number of forks
    - please let me know the number of forks in the repo
    - number of forks?
    - how many forks in total?
    - number of forks
    - forks count?
    - in this repository what is the total count of forks
    - count for me the number of forks that I have
    - let me know how many forks are in the repository
    - how many forks do I have?
    - how many forks in total does the repository have?
- intent: number_of_subscribers
  examples: |
    - count the repository subscribers
    - I want to know the number of subscribers in the repository
    - count all the subscribers for me
    - please let me know the number of subscribers in the repo
    - what is the number of subscribers
    - what is the number of subscribers that we have?
    - how many subscribers do I have
    - how many subscribers in total does the repository have?
    - count for me the number of subscribers that I have
    - subscribers count?
    - how many subscribers in total?
    - How many subscribers?
    - how many subscribers do I have?
    - In this repository, how many subscribers do I have?
- intent: list_collaborators
  examples: |
    - who are the collaborators?
    - who contributed to the repository?
    - Who are the repository contributors?
    - let me know who contributed to the repository
    - who collaborated on repository?
    - give me all the collaborators?
    - who collaborated in the repository?
    - list all the collaborators
    - Who are the repository collaborators?
    - who are the contributors?
    - who contributed to my repository?
    - who worked on this repository?
    - give me a list of all the contributors to the repository
    - give me a list of all the collaborators to the repository
    - list all the people who worked on the project
- intent: number_of_downloads
  examples: |
    - total number of downloads?
    - how many downloads
    - give the number of downloads I have in repository
    - I would like to know how many downloads are there in total?
    - how many downloads do I have?
    - count repository downloads
    - how many downloads do I have
    - count for me the number of downloads
    - how many downloads do we have?
    - In this repository, how many downloads do I have?
    - give me a count of all the downloads
    - how many downloads for the repository?
    - downloads count?
    - let me know how many downloads does the repository have
    - how many downloads in total does the repository have?
    - How many downloads?
- regex: filename
  examples: |
    - [^\\ ]*\.(\w+)
- regex: number
  examples: |
    - [0-9]+
