version: "2.0"
nlu:
- intent: issue_assignees
  examples: |
    - who is supposed to fix issue [62](issue_number)
    - Who is the assignee on issue [121](issue_number)
- intent: developers_with_most_open_issues
  examples: |
    - give me a list of developers with the most open issues
    - developers with most open issues
    - which developers are overloaded with open issues
- intent: list_releases
  examples: |
    - can you list the releases we have
    - what are the releases in this repository
- intent: last_developer_to_touch_a_file
  examples: |
    - who last commited with file [readme.md](filename)
    - show me the last person to change [actions.java](filename)
    - for file [map.json](filename) who was the last to touch it
- intent: number_of_commits_in_branch
  examples: |
    - how many commits are in the branch rel-1.3.0?
    - number of commits in the branch the-branch-name
    - How many commits are in the development branch
- intent: pr_assignees
  examples: |
    - pr [347](issue_number) assignees
    - assignee of pr [24](issue_number)
    - Who is the assignee on the pull request [121](issue_number)
- intent: number_of_collaborators
  examples: |
    - How many collaborators ?
    - how many contributors does this repository have
    - number of contributers on this repository
    - How many contributers ?
- intent: list_languages
  examples: |
    - What are the programming languages used in the repo
    - list me the language of this repostiory
    - technologies and languages used in the repo
- intent: intial_commit_in_branch
  examples: |
    - what was the message of the first commit in branch master
    - when was the first commit made in the master branch
    - who has the first commit to the add-ons branch
    - who has the first commit in branch xxyx
- intent: contributions_by_developer
  examples: |
    - How many commits does George have
    - What is the total number of contributions that Linus has made to this repository
    - Did Ben make alot of contributions to this repository ?
- intent: commits_in_pr
  examples: |
    - what are the commits in pull request [964](issue_number)
    - What are the commits for pr [6744](issue_number)
    - pr [13](issue_number) related commits
    - show me commits linked to pr [74](issue_number)
- intent: largest_files
  examples: |
    - List me the file with the most lines of code
    - file with most LOC
    - large files
    - give me the biggest file in the repository
- intent: latest_release
  examples: |
    - when did we last create a new release
    - latest release
    - newest release
    - last release
- intent: latest_commit
  examples: |
    - the last commit
    - can you tell me what the latest commit was
    - when was the last commit made
    - what is the last commit in the repository
- intent: latest_commit_in_branch
  examples: |
    - what is the last commit in the clean_tool branch
    - who made the last commit in master
    - the last commit to the XvX branch
    - who commited last to the master branch
- intent: longest_open_pr
  examples: |
    - what is the longest open pull request
    - which pr has been open for the longest time
    - Which pull requet has stayed open the longest
    - longest open pr
- intent: longest_open_issue
  examples: |
    - what is the longest open issue
    - oldest open issue ?
    - longest open issue
    - show me the longest open issue
- intent: activity_report
  examples: |
    - what happened yesterday
    - What happened in the last 24 hours
    - What were the recent events in the repository
    - what were the main events from the last day
    - show me the report for the day
- intent: issue_creation_date
  examples: |
    - What was the date when issue [432](issue_number) was created
    - when was issue [24](issue_number) created
    - can you tell me the date [2](issue_number) was opened ?
    - What was the date of creation issue [4](issue_number)
    - At what time was issue [2315](issue_number) opened
- intent: intial_commit
  examples: |
    - who made the 1st commited
    - what is the first commit ever
    - first commit
    - who has the first commit
    - when was the first commit made
- intent: number_of_prs
  examples: |
    - number of [closed](issue_status) prs
    - How many prs are currently [open](issue_status)
    - please provide a report about [closed](issue_status) pull requests in the repo
    - what is the number of [closed](issue_status) pull requests
    - I want to know the number of pulls
- intent: pr_creation_date
  examples: |
    - pull request [546](issue_number) creation date
    - At what time was the pull request [2315](issue_number) opened
    - pr [546](issue_number) creation date
    - when was pr [24](issue_number) created
    - When was pull request [1109](issue_number) opened
- intent: number_of_issues
  examples: |
    - For this repo, show me the the number of [open](issue_status) issues
    - number of [closed](issue_status) issues
    - How many [open](issue_status) issues
    - Give me the bugs report
    - How many bugs are currently [open](issue_status)
- intent: most_recent_prs
  examples: |
    - show me the most recent prs
    - newest prs
    - what are the newest prs
    - show me the newest pull requests in the repository
    - when was the most recent PR?
    - most recent pull requests
- intent: files_changed_by_pr
  examples: |
    - file changes by pr [84161](issue_number)
    - show me a list of changed files in pr [6744](issue_number)
    - what are the file changes introduced by [6744](issue_number)
    - In pull request [6744](issue_number), what files changed
    - give me a list of files that were changed by pull request [564](issue_number)
- intent: most_recent_issues
  examples: |
    - latest opened issues
    - newest issues
    - latest issues
    - list recent issues
    - list the recent open issues
    - show me the most recent issues
- intent: top_contributors
  examples: |
    - list the top contributors
    - who are the active developers?
    - Who committed the most to this repository
    - who is the top contributor
    - show me the list of the top contributers
    - who has the most commits
- intent: pr_closing_date
  examples: |
    - when did we merge pr [3907](issue_number)
    - When was pull request [1109](issue_number) closed
    - When did pr [214](issue_number) finally close
    - pull request [546](issue_number) close date
    - show me the closing date for pull request [3](issue_number)
    - What was the date of closing pr [4](issue_number)
- intent: issue_closing_date
  examples: |
    - when did we close issue [4783](issue_number)
    - when was issue [674](issue_number) resolved
    - was issue [24](issue_number) closed ?
    - When was issue [1109](issue_number) closed
    - closing date issue [860](issue_number)
    - At what time was issue [2315](issue_number) closed
    - issue [546](issue_number) closing date
- intent: issue_creator
  examples: |
    - show me issue [84161](issue_number) creator
    - did this person open [78](issue_number)
    - who opened issue [6744](issue_number)
    - who is the developer that opened issue [964](issue_number)
    - issue [774](issue_number) opener
    - issue [13](issue_number) creator
- intent: pr_contributors
  examples: |
    - give me names of all the commenters on pr [6681](issue_number)
    - who contributed to pr [6744](issue_number)
    - give me names of all the contributors to pr [123](issue_number)
    - show me who helped on pr [1235](issue_number)
    - who are the people who commented on pr [9521](issue_number)
    - contributors to pr [3234](issue_number)
    - give me a list of developers who contributed to pr [564](issue_number)
- intent: pr_creator
  examples: |
    - creator of pull request [3234](issue_number)
    - who is the developer that started pull request [964](issue_number)
    - who created pull request [6744](issue_number)
    - show me who created pr [74](issue_number)
    - who opened pr [9521](issue_number)
    - give me a the developer name who created pull request [564](issue_number)
- intent: pr_closer
  examples: |
    - who closed pr [6744](issue_number)
    - who closed pull request [9521](issue_number)
    - merger of pr [9521](issue_number)
    - show me who closed pull request [1235](issue_number)
    - who is the developer that merged pull request [964](issue_number)
    - show me who closed pr [74](issue_number)
    - give me the user that merged pr [888](issue_number)
- intent: number_of_watchers
  examples: |
    - how many watchers do we have?
    - how many watchers in total does the repository have?
    - how many people are watching the repository?
    - I want to know the number of people watching the the repository
    - number of watchers?
    - what is the number of watchers
- intent: main_programming_language
  examples: |
    - which language are we using the most?
    - which programming language do we use the most?
    - Give me the language that is used to program in the repository
    - Tell me the dominant programming language
    - most used programming language
    - Main programming language?
    - what is the main language of this repository
- intent: issue_closer
  examples: |
    - issue [13](issue_number) closer
    - who is responsible for closing issue [44](issue_number)
    - issue [774](issue_number) resolver
    - closer of issue [3234](issue_number)
    - who closed issue [6744](issue_number)
    - show me who closed issue [1235](issue_number)
    - who resolved issue [9521](issue_number)
- intent: default_branch
  examples: |
    - what is the main branch in this repository
    - Default branch?
    - let me know which branch is the main one?
    - Which branch is considered as default
    - base branch?
    - give me the main branch in the repository?
    - what is the base branch in this repository?
- intent: repository_owner
  examples: |
    - I would like to know the person who owns the repository
    - Who owns the repository?
    - who owns repository?
    - tell me the name of the repository owner
    - what is the name of the repository owner?
    - what is the name of the person who owns the repository
    - Who is the repository owner
- intent: repository_license
  examples: |
    - legal license?
    - what is the license for the repository ?
    - what is the legal license in this repository?
    - I want to know the licences in our repository
    - I would like to know the repository license
    - What licences do we have?
    - license for the repository?
- intent: issue_contributors
  examples: |
    - give me a list of developers who contributed to issue [564](issue_number)
    - issue [13](issue_number) contributors
    - who touched [98](issue_number)
    - who are the contributors to issue [964](issue_number)
    - issue [774](issue_number) commenters
    - show me issue [84161](issue_number) contributors
    - show me the developers who commented on issue [888](issue_number)
- intent: repository_topics
  examples: |
    - give me the topics that are related to repository
    - list me all the topics for this repository
    - give me the topics for this repository
    - what topics do we have in this repository?
    - what are the repository topics
    - repository topics that we have?
    - what are the topics for the repository ?
    - what topics does my repository have?
    - I'd like to know the repository topics
- intent: repository_creation_date
  examples: |
    - what was our repository created?
    - project creation date
    - repository creation date
    - when was this repository created?
    - at what date was the repository created?
    - when did we create the repository
    - what is the creation dete for the repository
    - when did this repository start
- intent: file_creator
  examples: |
    - who created this file [index.js](filename)
    - I would like to know who first created file [tf_env_collect.sh](filename)?
    - who created file [readme.md](filename) in the repository?
    - creator of file [server.json](filename)
    - show me who created the file [bridge.py](filename)
    - who created file [pyproject.toml](filename) in repository
    - who created file [index.js](filename)?
    - developer who created [constant.txt](filename)
    - tell me the developer name who created file [gitignore](filename)
    - give me the name of the developer who created file [index.html](filename)
- intent: issue_related_commits
  examples: |
    - show me commits linked to this issue [3234](issue_number)?
    - show me commits related to this issue [3234](issue_number)?
    - which commits in the repository are related to issue [84161](issue_number)?
    - show me the related commits to issue [84161](issue_number)
    - which commits mentioned issue [9521](issue_number)
    - give me a the commits related to issue [564](issue_number)
    - issue [13](issue_number) related commits?
    - commits linked to issue [3234](issue_number)
    - what commits were mentioned issue [74](issue_number)?
- intent: list_branches
  examples: |
    - name all the branches in the repository
    - what are the branches in the repository
    - what branches do I have
    - list all branches please
    - what are the branches that are in the repository?
    - let me know the names of all branches
    - list branches
    - what are the names of all the branches
    - give me a list of all the branches in the repository
    - Give me a list of the branches
- intent: number_of_branches
  examples: |
    - How many branches?
    - number of branches
    - count for me the number of branches that I have
    - please let me know the number of branches in the repo
    - count the repository branches
    - branches count
    - what is the number of branches that we have?
    - how many branches do I have
    - I want to know the number of branches in the repository
    - In this repository, how many branches do I have?
    - give the number of branches I have in repository
    - count for me the number of branches
    - let me know how many branches are in the repository
- intent: number_of_commits
  examples: |
    - how many commits in total does the repository have?
    - I would like to know how many commits are there in total?
    - let me know how many commits are in the repository
    - give me a count of all the commits
    - provide me with the total number of commits
    - commits count
    - I want to know the number of commits in the repository
    - commits count?
    - what is the number of commits
    - count for me the number of commits
    - how many commits
    - please let me know the number of commits in the repo
    - give me the commit count in my repoisotry
- intent: number_of_forks
  examples: |
    - how many forks do we have?
    - give me a count of all the forks
    - how many forks
    - How many forks?
    - I would like to know how many forks are there in total?
    - how many forks do I have?
    - how many forks in the repository?
    - how many forks in total does the repository have?
    - count for me the number of forks that I have
    - how many forks in total?
    - count for me the number of forks
    - how many forks do I have
    - forks count
- intent: number_of_subscribers
  examples: |
    - what is the number of subscribers that we have?
    - let me know how many subscribers are in the repository
    - In this repository, how many subscribers do I have?
    - how many subscribers do we have?
    - give me the subscriber count in my repoisotry
    - count the repository subscribers
    - give the number of subscribers I have in repository
    - How many subscribers?
    - how many subscribers in the repository?
    - how many subscribers in total?
    - how many subscribers do I have
    - how many subscribers in total does the repository have?
    - I want to know the number of subscribers in the repository
- intent: number_of_stars
  examples: |
    - count for me the number of stars
    - please let me know the number of stars in the repo
    - how many stars do I have?
    - In this repository, how many stars do I have?
    - how many stars in the repository?
    - how many stars
    - how many stars do we have?
    - How many stars?
    - I would like to know how many stars are there in total?
    - count for me the number of stars that I have
    - count the repository stars
    - number of stars
    - number of stars?
- intent: list_collaborators
  examples: |
    - who contributed to my repository?
    - let me know who contributed to the repository
    - who has worked on our project?
    - who contributed to our project?
    - list who worked on this project
    - please give me the names of the repository collaborators
    - list me all the people who helped in this project?
    - list the names of all the contributors?
    - Who committed in this repository?
    - list all the people who worked on the project
    - list all the workers on this repository
    - give me a list of all the contributors to the repository
    - tell me who worked on the repository
    - who are the contributors?
- intent: number_of_downloads
  examples: |
    - I would like to know how many downloads are there in total?
    - count the repository downloads
    - give me the download count in my repoisotry
    - give the number of downloads I have in repository
    - provide me with the total number of downloads
    - how many downloads in total?
    - number of downloads?
    - In this repository, how many downloads do I have?
    - how many downloads do I have
    - let me know how many downloads does the repository have
    - what is the number of downloads that we have in repository?
    - downloads count
    - how many downloads for the repository?
    - give me a count of all the downloads
- regex: filename
  examples: |
    - [^\\ ]*\.(\w+)
- regex: number
  examples: |
    - [0-9]+
