version: "2.0"
nlu:
- intent: issue_assignees
  examples: |
    - Who should fix issue [1](issue_number)
- intent: developers_with_most_open_issues
  examples: |
    - which developers are overloaded with open issues
- intent: list_releases
  examples: |
    - give me a list of the releases in the repository
- intent: last_developer_to_touch_a_file
  examples: |
    - who was the last developer to change file [index.js](filename)
- intent: number_of_commits_in_branch
  examples: |
    - commits in branch xywz
- intent: pr_assignees
  examples: |
    - pr [347](issue_number) assignees
- intent: list_languages
  examples: |
    - list me the language of this repostiory
- intent: intial_commit_in_branch
  examples: |
    - what was the message of the first commit in branch master
- intent: commits_in_pr
  examples: |
    - what are the commits linked to pr [6744](issue_number)
- intent: latest_commit
  examples: |
    - what is the last commit in the repository
- intent: number_of_collaborators
  examples: |
    - how many contributors does this repository have
- intent: contributions_by_developer
  examples: |
    - How much did John contribute to the respository ?
- intent: largest_files
  examples: |
    - longest file size
    - largest file in size
- intent: latest_release
  examples: |
    - when was the latest release published
- intent: latest_commit_in_branch
  examples: |
    - who made the last commit in master
    - the last commit to the XvX branch
- intent: longest_open_pr
  examples: |
    - which pr has been open the longest
- intent: longest_open_issue
  examples: |
    - which issue has been open the longest
    - what is the longest open issue
- intent: activity_report
  examples: |
    - give me a report from the last day?
- intent: issue_creation_date
  examples: |
    - issue [546](issue_number) creation date
    - show me the creation date for issue [3](issue_number)
- intent: intial_commit
  examples: |
    - what is the first commit ever
- intent: pr_creation_date
  examples: |
    - What was the date when pull request with number [432](issue_number) was created
    - When was pull request [1109](issue_number) opened
- intent: number_of_issues
  examples: |
    - what is the number of [closed](issue_status) issues
- intent: top_contributors
  examples: |
    - who is the top contributor
    - Who committed the most to this repository
- intent: number_of_prs
  examples: |
    - Give me the total number of pulls in the repository
    - count pulls
- intent: most_recent_prs
  examples: |
    - list recent prs
    - give me a list of the most recent prs
- intent: files_changed_by_pr
  examples: |
    - give me a list of files that were changed by pull request [564](issue_number)
    - list me the files affected by pr number [4](issue_number)
- intent: most_recent_issues
  examples: |
    - list recent issues
    - show me the latest issues
- intent: pr_closing_date
  examples: |
    - pr [546](issue_number) closing date
    - What was the date of closing pr [4](issue_number)
- intent: issue_creator
  examples: |
    - issue [13](issue_number) creator
    - who opened issue [9521](issue_number)
- intent: pr_contributors
  examples: |
    - show me the developers who commented on pr [888](issue_number)
    - who contributed to pr [6744](issue_number)
- intent: pr_creator
  examples: |
    - who is the developer that started pull request [964](issue_number)
    - who authored pull request [3](issue_number)?
- intent: pr_closer
  examples: |
    - give me a the developer name who closed pull request [564](issue_number)
    - give me the user that merged pr [888](issue_number)
- intent: number_of_watchers
  examples: |
    - how many watchers do we have?
    - I want to know the number of people watching the the repository
- intent: main_programming_language
  examples: |
    - give me the main programming language
    - most used programming language
- intent: issue_closing_date
  examples: |
    - When was issue [1109](issue_number) closed
    - issue [546](issue_number) closing date
- intent: issue_closer
  examples: |
    - issue [774](issue_number) resolver
    - show me who closed issue [74](issue_number)
    - issue [13](issue_number) closer
- intent: default_branch
  examples: |
    - which branch is deafualt out of the ones we have?
    - Default branch?
- intent: repository_owner
  examples: |
    - who has ownership over this repository
    - Who is the repository owner
    - who owns repository?
- intent: repository_license
  examples: |
    - Under which license does the repository work
    - what is the legal licences
- intent: issue_contributors
  examples: |
    - who are the people who commented on issue [9521](issue_number)
    - give me names of all the contributors to issue [123](issue_number)
    - who touched [98](issue_number)
- intent: repository_topics
  examples: |
    - topics for this repository?
    - what topics does my repository have?
- intent: repository_creation_date
  examples: |
    - I want to know th ecreation date of repository
    - what was our repository created?
    - give me the creation date for the repository
- intent: file_creator
  examples: |
    - who created the file [index.js](filename)?
    - tell me the developer name who created file [gitignore](filename)
    - who created file [index.js](filename)?
- intent: list_branches
  examples: |
    - give me the branches that we have
    - I want to know what are the branches in the repository right now
    - list the names of branches
- intent: issue_related_commits
  examples: |
    - what commits are linked to [3234](issue_number)?
    - show me the related commits to issue [84161](issue_number)
    - in which commits was issue [964](issue_number)?
    - issue [13](issue_number) linked commits?
- intent: number_of_commits
  examples: |
    - number of commits
    - give me a count of all the commits
    - number of commits?
    - commits count
- intent: number_of_branches
  examples: |
    - how many branches do I have?
    - how many branches in total?
    - in this repository what is the total count of branches
    - I would like to know how many branches are there in total?
- intent: number_of_stars
  examples: |
    - how many stars do we have?
    - provide me with the total number of stars
    - stars count
    - I want to know the number of stars in the repository
    - number of stars?
- intent: number_of_forks
  examples: |
    - give the number of forks I have in repository
    - total number of forks?
    - what is the number of forks that we have?
    - I want to know the number of forks in the repository
- intent: number_of_subscribers
  examples: |
    - what is the number of subscribers
    - how many subscribers in total?
    - count all the subscribers for me
    - total number of subscribers?
    - provide me with the total number of subscribers
- intent: list_collaborators
  examples: |
    - who collaborated on repository?
    - who contributed to the repository?
    - who worked on this repository?
    - give me all the contributors?
- intent: number_of_downloads
  examples: |
    - count for me the number of downloads that I have
    - I would like to know how many downloads are there in total?
    - provide me with the total number of downloads
    - count the repository downloads
    - in this repository what is the total count of downloads
- regex: filename
  examples: |
    - [^\\ ]*\.(\w+)
- regex: number
  examples: |
    - [0-9]+
