version: "2.0"
nlu:
- intent: issue_assignees
  examples: |
    - Who are the assignees on issue [1](issue_number)
- intent: developers_with_most_open_issues
  examples: |
    - who has the most open issues
    - which developers are overloaded with open issues
- intent: list_releases
  examples: |
    - list releases
- intent: number_of_commits_in_branch
  examples: |
    - number of commits in the branch the-branch-name
    - how many commits are in the documentation branch
- intent: last_developer_to_touch_a_file
  examples: |
    - who last changed [main.py](filename)
    - who was the last developer to change file [index.js](filename)
- intent: pr_assignees
  examples: |
    - pr [347](issue_number) assignees
    - which developers should work on pull request [5](issue_number)
- intent: number_of_collaborators
  examples: |
    - How many contributers ?
    - How many developers have commited to this repo
- intent: list_languages
  examples: |
    - technologies and languages used in the repo
    - What are the technologies that are used in this repository ?
- intent: intial_commit_in_branch
  examples: |
    - the inital commit for branch master
    - when was the first commit made in the master branch
- intent: contributions_by_developer
  examples: |
    - How many commits are done by developer X?
    - How many contributions does Makram have
- intent: commits_in_pr
  examples: |
    - show me pull request [84161](issue_number) related commits
    - give me a list of commits related to pull request [564](issue_number)
- intent: largest_files
  examples: |
    - file with most LOC
    - largest file in size
- intent: latest_commit
  examples: |
    - who commited last
    - can you tell me what the latest commit was
- intent: longest_open_pr
  examples: |
    - which pr has been open for the longest time
    - longest open pr
- intent: latest_release
  examples: |
    - give me the last release for the repository
    - newest release
- intent: latest_commit_in_branch
  examples: |
    - last in commit in branch XYZ
    - who made the last commit in master
    - the latest commit in the branch master
- intent: longest_open_issue
  examples: |
    - which issue has been open the longest
    - what is the longest open issue
- intent: activity_report
  examples: |
    - show me the report for the day
    - repository activity in the last day ?
    - What were the recent events in the repository
- intent: intial_commit
  examples: |
    - who made the 1st commited
    - who has the initial commit in the repository
- intent: pr_creation_date
  examples: |
    - When was pull request [1109](issue_number) opened
    - What was the date when pull request with number [432](issue_number) was created
    - show me the creation date for pr [3](issue_number)
- intent: issue_creation_date
  examples: |
    - When was issue [1109](issue_number) opened
    - What was the date of creation issue [4](issue_number)
    - when did we open issue [4783](issue_number)
- intent: number_of_prs
  examples: |
    - number of pull requests
    - what is the number of [closed](issue_status) pull requests
    - count pulls
- intent: number_of_issues
  examples: |
    - what is the number of [closed](issue_status) issues
    - count [open](issue_status) issues
    - please provide a report about [closed](issue_status) issues in the repo
- intent: most_recent_prs
  examples: |
    - show me the newest pull requests in the repository
    - give me a list of the most recent prs
    - what are the most recent pull requests
- intent: files_changed_by_pr
  examples: |
    - list me the files affected by pr number [4](issue_number)
    - list the changed files in pull request [964](issue_number)
    - what are the file changes introduced by [6744](issue_number)
- intent: top_contributors
  examples: |
    - who has the highest number of commits
    - list the top contributors
    - who is the top contributor
- intent: most_recent_issues
  examples: |
    - show me the newest issues in the repository
    - give me a list of the most recent issues
    - list the recent open issues
- intent: pr_closing_date
  examples: |
    - show me the closing date for pull request [3](issue_number)
    - when was pr [24](issue_number) closed
    - What was the date of closing pr [4](issue_number)
    - when did we merge pr [3907](issue_number)
- intent: issue_closing_date
  examples: |
    - What was the date of closing issue [4](issue_number)
    - What was the date when issue [432](issue_number) was resolved
    - when was issue [674](issue_number) resolved
- intent: issue_creator
  examples: |
    - give me the user that opened issue [888](issue_number)
    - show me who opned issue [1235](issue_number)
    - who is the developer that opened issue [964](issue_number)
    - did this person open [78](issue_number)
- intent: pr_contributors
  examples: |
    - show me pr [84161](issue_number) contributors
    - give me names of all the commenters on pr [6681](issue_number)
    - pr [13](issue_number) contributors
- intent: pr_creator
  examples: |
    - who opened pr [9521](issue_number)
    - show me pull request [84161](issue_number) creator
    - give me a the developer name who created pull request [564](issue_number)
    - show me who opned pull request [1235](issue_number)
- intent: pr_closer
  examples: |
    - pr [774](issue_number) merger
    - who merged pr [3234](issue_number)
    - who is the developer that merged pull request [964](issue_number)
- intent: issue_closer
  examples: |
    - show me who closed issue [74](issue_number)
    - issue [13](issue_number) closer
    - closer of issue [3234](issue_number)
    - resolver of issue [3234](issue_number)
- intent: default_branch
  examples: |
    - base branch?
    - give me the main branch in the repository?
    - what is the base branch in the repository
- intent: repository_owner
  examples: |
    - what is the name of the person who owns the repository
    - who has ownership over this repository
    - To whom does this repo belong?
    - I'd like to know the repository owner
- intent: number_of_watchers
  examples: |
    - How many watchers?
    - watchers count?
    - I want to know the number of people watching the the repository
    - how many watchers
- intent: main_programming_language
  examples: |
    - Give me the language that is used to program in the repository
    - Tell me the dominant programming language
    - what is the main language of this repository
    - most used programming language
- intent: repository_license
  examples: |
    - what is the legal licences
    - legal license?
    - What licences do we have?
    - I would like to know the repository license
- intent: issue_contributors
  examples: |
    - give me a list of developers who contributed to issue [564](issue_number)
    - who are the contributors to issue [964](issue_number)
    - give me names of all the contributors to issue [123](issue_number)
    - who worked on [33](issue_number)
- intent: repository_topics
  examples: |
    - what are the topics for the repository ?
    - To which topics does the repository belong
    - what topics do we have
    - I would like to know the topics in the repository we have
    - topics related to the repository?
- intent: repository_creation_date
  examples: |
    - what was our repository created?
    - at what time was this repository created
    - When did this project start?
    - project creation date
- intent: file_creator
  examples: |
    - who added the file [response.java](filename) ?
    - developer who created [constant.txt](filename)
    - creator of file [server.json](filename)
    - I want to know who created file [map.json](filename)
    - I would like to know who first created file [tf_env_collect.sh](filename)?
    - who created file [index.js](filename)?
- intent: issue_related_commits
  examples: |
    - list commits that mention issue [84161](issue_number)
    - which commits in the repository are linked to issue [84161](issue_number)?
    - which commits mentioned issue [9521](issue_number)
    - give me a list of all the commits where issue [1235](issue_number) was mentioned
    - issue [13](issue_number) linked commits?
- intent: list_branches
  examples: |
    - list branches
    - name all the branches
    - I want to know what are the branches in the repository right now
    - name all the branches in the repository
    - what branches do I have
    - what are the branches in the repository
- intent: number_of_branches
  examples: |
    - please let me know the number of branches in the repo
    - how many branches do we have?
    - provide me with the total number of branches
    - How many branches?
    - let me know how many branches are in the repository
    - how many branches in total does the repository have?
    - give the number of branches I have in repository
- intent: number_of_commits
  examples: |
    - In this repository, how many commits do I have?
    - give me the commit count in my repoisotry
    - how many commits
    - number of commits
    - count for me the number of commits that I have
    - I want to know the number of commits in the repository
    - count the repository commits
- intent: number_of_forks
  examples: |
    - what is the number of forks that we have?
    - I would like to know how many forks are there in total?
    - In this repository, how many forks do I have?
    - how many forks do I have
    - count the repository forks
    - I want to know the number of forks in the repository
    - forks count
- intent: number_of_stars
  examples: |
    - count the repository stars
    - how many stars do we have?
    - In this repository, how many stars do I have?
    - stars count
    - what is the number of stars that we have?
    - how many stars do I have?
    - give me a count of all the stars
- intent: number_of_subscribers
  examples: |
    - number of subscribers
    - total number of subscribers?
    - subscribers count
    - how many subscribers
    - how many subscribers do we have?
    - give the number of subscribers I have in repository
    - provide me with the total number of subscribers
    - let me know how many subscribers are in the repository
- intent: list_collaborators
  examples: |
    - who contributed to our project?
    - list all the contributors
    - list the names of all the contributors?
    - tell me all the people who contributed to my project
    - list me all the people who helped in this project?
    - give me the name of people who worked on this project?
    - please give me the names of the repository collaborators
- intent: number_of_downloads
  examples: |
    - count for me the number of downloads that I have
    - number of downloads
    - what is the number of downloads
    - I want to know the number of downloads for the repository
    - provide me with the total number of downloads
    - what is the number of downloads that we have in repository?
    - number of downloads?
    - downloads count
- regex: filename
  examples: |
    - [^\\ ]*\.(\w+)
- regex: number
  examples: |
    - [0-9]+
